# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def test_pods
  pod 'Nimble', '~> 8.0.1'
  pod 'Quick', '~> 2.0.0'
end

def app_pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'KRProgressHUD', '~> 3.4.0'
end

target 'KcalLogger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  app_pods

end

target 'KcalLoggerTests' do
    inherit! :search_paths
    app_pods
    test_pods
  end

  target 'KcalLoggerUITests' do
    inherit! :search_paths
    app_pods
    test_pods
  end

# Disable Code Coverage for Pods projects
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end
